# Numpy

## Basics

In [20]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [25]:
arr2 = np.zeros((2,3,4))
print(arr2)
arr2 = np.empty((4,3))
arr2.dtype=np.int64
print(arr2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
arr = np.arange(3, 31, 3, dtype=np.float32).reshape(2,5)
print(arr)

[[ 3.  6.  9. 12. 15.]
 [18. 21. 24. 27. 30.]]


## Arithmetic

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
arr=arr*12
print(arr)
arr=arr/3
print(arr)
arr=arr+22
print(arr)

[[12 24 36]
 [48 60 72]]
[[ 4.  8. 12.]
 [16. 20. 24.]]
[[26. 30. 34.]
 [38. 42. 46.]]
