# Practice Questions

## Basics

1. Empty and full numpy arrays

In [3]:
import numpy as np
e  = np.empty((3,4), np.float64)
print(e)

f = np.full((3,4), 20)
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


2. arrays filled with zeroes or ones

In [4]:
z = np.zeros((3,3))
o = np.ones((3,3))
print(z, o)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. Check whether a row in present in numpy array

In [10]:
r = np.array([[1,2,3],[4,5,6],[7,8,9]])
print([1,2,4] in r.tolist())
print([1,2,3] in r.tolist())


False
True


4. Remove rows in Numpy array that contains non-numeric values?

In [14]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


5. Find the number of occurrences of a sequence in a NumPy array

In [17]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

ans  = repr(arr).count("9, 4")
ans



4

5. Find the most frequent value in a NumPy array

In [20]:
arr = np.array([1,1,2,3,4,5,1,2,2,5,6])
c = np.bincount(arr)
m = max(c)
print(m)

for i in range(len(c)):
    if c[i] == m:
        print(i, end=" ")

3
1 2 

6. Add 1d and 2d array

In [21]:
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([7,8,9])
arr3=arr+arr2
print(arr3)

[[ 8 10 12]
 [11 13 15]]


7. flatten a matrix

In [22]:
arr = np.array([[1,2,3], [4,5,6]])
arr.flatten()

array([1, 2, 3, 4, 5, 6])

8. count non-zero numbers

In [25]:
arr = np.array([[1,2,3], [4,5,6]])

np.count_nonzero(arr)

6

9. number of row along axes

In [26]:
arr = np.array([[1,2,3], [4,5,6]])

print(np.size(arr, 0))
print(np.size(arr, 1))


2
3


10. trimming leading and trailing zeroes

In [31]:
arr = np.array([0,0,0,1,3,4,5,3,2,0,0,0])
print(np.trim_zeros(arr))
print(np.trim_zeros(arr, 'f'))
print(np.trim_zeros(arr, 'b'))


[1 3 4 5 3 2]
[1 3 4 5 3 2 0 0 0]
[0 0 0 1 3 4 5 3 2]


11. Change datatype of given numpy array

In [41]:
arr = np.array([[1,2,3], [4,5,6]])
arr = arr.astype(np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

12. Reverse a numpy array


In [46]:
arr = np.array([1,1,2,3,4,5,1,2,2,5,6])
np.flip(arr)

array([6, 5, 2, 2, 1, 5, 4, 3, 2, 1, 1])

1. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [5]:
import numpy as np

arr = np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [7]:
arr = np.zeros(10, np.float32)
print(arr)
arr[7]=11
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0.  0. 11.  0.  0.]


3. Write a NumPy program to reverse an array (first element becomes last

In [9]:
arr = np.arange(12, 38)
print(arr)
print(np.flip(arr))


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


4. Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [13]:
arr = np.ones((5,5))
arr[1:-1, 1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

5. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [15]:
arr = np.zeros((8,8))
arr[1::2, ::2]=1
arr[::2, 1::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

6. Write a NumPy program to append values to the end of an array

In [19]:
arr = np.array([10, 20, 30])
arr=np.append(arr, [40, 50, 60, 70, 80, 90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

7. Convert the values of Centigrade degrees into Fahrenheit degrees and vice versa

In [22]:
f = np.array([0, 12, 45.21, 34, 99.91])
c=np.round(((5*f)/9-(5*32)/9), 2)
c

array([-17.78, -11.11,   7.34,   1.11,  37.73])

8. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [25]:
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([0,40])

print(np.in1d(arr1, arr2))

[ True False False  True False]


9. Unique elements

In [26]:
arr = np.array([1,1,2,2,2,3,3,2,1,4,5,5])
print(np.unique(arr))

[1 2 3 4 5]


10. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [27]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([20, 50, 30, 60, 70])
print(np.union1d(arr1, arr2))

[10 20 30 40 50 60 70]


11. Write a NumPy program to construct an array by repeating.

In [30]:
arr = np.array([1,2,3,4])
print(np.tile(arr, 4).reshape((4,4)))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


12. Write a NumPy program to sort an along the first, last axis of an array

In [35]:
arr = np.array([[4,6],[2,1]])
print(np.sort(arr, 0))
arr.dtype

[[2 1]
 [4 6]]


dtype('int64')

13. Write a NumPy program to create a 2-D array with ones on a diagonal and zeros elsewhere.

In [38]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

14. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

In [39]:
arr = np.diagflat([[4,5,6,8]])
arr

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

## Linear Algebra

1. Matrix multiplication

In [3]:
import numpy as np
arr1 = np.array([[1,0],[0,1]])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.dot(arr1, arr2)
arr3

array([[1, 2],
       [3, 4]])

2. Outer product of two vectors

In [4]:
arr1 = np.array([[1,0],[0,1]])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.outer(arr1,arr2)
arr3

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

3. cross product

In [10]:
arr1 = [[1, 0], [0, 1]]
arr2 = [[1, 2], [3, 4]]
arr3 = np.cross(arr1, arr2)
arr3

array([ 2, -3])

4. Determinant

In [11]:
arr = np.array([[1,2], [3,4]])
det = np.linalg.det(arr)
det

-2.0000000000000004

5. Inverse

In [12]:
arr = np.array([[1,2], [3,4]])
inv = np.linalg.inv(arr)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

6. Trace of a matrix

In [16]:
arr = np.array([[1,2], [3,4]])
tr = np.trace(arr)
tr

5

## Searching and Sorting

1. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [19]:
data_type = [('name', 'S15'), ('class', 'int'), ('height', 'float')]
data = [("James", 5, 48.5), ('Neil', 6, 52.5), ('Paul', 5, 42.1), ('Pit',5,40.11)]
arr = np.array(data, data_type)
print(np.sort(arr, order='height', ))

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Neil', 6, 52.5 )]


2. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

In [26]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])

indices = np.lexsort((student_id, student_height))

for i in indices:
    print(student_height[i], " ", student_id[i])


38.0   1682
40.0   1023
40.0   5241
41.0   1671
42.0   4532
42.0   5202
45.0   6230


3. Write a NumPy program to get the indices of the sorted elements of a given array.

In [27]:
arr = np.array([1023,5202, 6230, 1671, 1682, 5241, 4532])
sort = np.argsort(arr)
sort

array([0, 3, 4, 6, 1, 5, 2])

## Mathematics

1. Write a NumPy program to get true division of the element-wise array inputs.

In [2]:
import numpy as np
arr = np.array(range(0,10))
arr/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

2. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.

In [7]:
arr = np.array(range(1,5))
print(np.floor_divide(arr, 1.5))


[0. 1. 2. 2.]


3. Write a NumPy program to get the powers of an array values element-wise.

In [9]:
arr = np.array(range(0,7))
pow = np.power(arr, 3)
pow

array([  0,   1,   8,  27,  64, 125, 216])

4. Write a NumPy program to get the element-wise remainder of an array of division.

In [10]:
arr = np.array(range(0,7))
rem = np.remainder(arr, 5)
rem

array([0, 1, 2, 3, 4, 0, 1])

5. Write a NumPy program to get the element-wise remainder of an array of division.

In [11]:
arr = np.array([-10.2, 122.2, 0.2])
abs  = np.abs(arr)
abs

array([ 10.2, 122.2,   0.2])

6. Write a NumPy program to round array elements to the given number of decimals.

In [12]:
arr = np.array([-10.2, 122.2, 0.2])
round  = np.round(arr, 0)
round

array([-10., 122.,   0.])

7. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

In [19]:
arr1 = np.random.rand(15).reshape(5,3)
arr2 = np.random.rand(6).reshape(3,2)
ans  = np.dot(arr1, arr2)
ans



array([[0.85566993, 0.74218975],
       [1.30116108, 1.30393515],
       [1.28609351, 1.04271415],
       [1.13583371, 0.81664409],
       [0.7028658 , 0.88982602]])

8. Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.

In [20]:
arr1 = np.array([1, 4, 0])
arr2 = np.array([2,2,1])

print(np.inner(arr1, arr2))
print(np.outer(arr1, arr2))
print(np.cross(arr1, arr2))

10
[[2 2 1]
 [8 8 4]
 [0 0 0]]
[ 4 -1 -6]


In [23]:
x = np.array([[1,0], [1,1]])
y = np.array([[3, 1], [2,2]])
print(np.matmul(x,y))
print(np.dot(x, y))

[[3 1]
 [5 3]]
[[3 1]
 [5 3]]


## Statistics

1. Write a Python program to find the maximum and minimum value of a given flattened array.

In [5]:
import numpy as np
arr = np.array(range(0,4))
print(np.max(arr))
print(np.min(arr))


3
0


2. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

In [6]:
import numpy as np
arr = np.array(range(0,4)).reshape((2,2))
print(np.max(arr,1))
print(np.min(arr,1))


[1 3]
[0 2]


3. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.



In [9]:
arr = np.arange(12).reshape((2,6))
r1 = np.ptp(arr,1)
r1

array([5, 5])

4. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.

In [20]:
arr = np.array(range(1, 21)).reshape((2,10))
print(arr)
p = np.percentile(arr, 80, 1)
p

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


array([ 8.2, 18.2])

5. Write a NumPy program to compute the median of flattened given array.

In [2]:
import numpy as np
arr = np.arange(12).reshape((2, 6))
median = np.median(arr)
median

5.5

6. Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis

In [3]:
arr = np.arange(6)
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

2.5
1.707825127659933
2.9166666666666665


7. Write a NumPy program to compute the covariance matrix of two given arrays.

In [4]:
arr = np.array([0,1,2])
arr2 = np.array([2,1,0])
cov = np.cov(arr, arr2)
cov

array([[ 1., -1.],
       [-1.,  1.]])